apiVersion: v1
kind: Secret
metadata:
  name: fiap-backend-secret
  namespace: fiap-backend
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=host.docker.internal;Port=5432;Database=fiap_tech_challenge;Username=postgres;Password=postgres"
  Jwt__SigningKey: "8b301d30-2445-45e4-8d75-727c8d4001c2"
