apiVersion: v1
kind: Service
metadata:
  name: fiap-backend-service
  namespace: fiap-backend
spec:
  type: ClusterIP
  selector:
    app: fiap-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
