apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-backend-deployment
  namespace: fiap-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-backend
  template:
    metadata:
      labels:
        app: fiap-backend
    spec:
      containers:
        - name: fiap-backend
          image: 575638747623.dkr.ecr.us-east-1.amazonaws.com/fiap-ecr-backend-repository:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: fiap-backend-config
            - secretRef:
                name: fiap-secret-manager-database-credentials
            - secretRef:
                name: fiap-secret-manager-jwt-signing-key
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/health/live
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
