apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fiap-secret-manager-database-credentials
  namespace: fiap-backend
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore

  target:
    name: fiap-secret-manager-database-credentials
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: fiap-secret-manager-database-credentials

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fiap-secret-manager-jwt-signing-key
  namespace: fiap-backend
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore

  target:
    name: fiap-secret-manager-jwt-signing-key
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: fiap-secret-manager-jwt-signing-key