apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fiap-backend-secret
  namespace: fiap-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore

  target:
    name: fiap-backend-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: fiap-secret-manager-backend
