name: Push Frontend

env:
  AWS_REGION: 'us-east-1'
  ECR_REPOSITORY: 'fiap-ecr-frontend-repository'
  IMAGE_TAG: ${{ github.sha }}

  DOCKERFILE_PATH: './src/FIAP.TechChallenge.Fase1.Frontend/Dockerfile' 
  DOCKER_BUILD_CONTEXT: './src/FIAP.TechChallenge.Fase1.Frontend' 

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-docker:
    name: Build e Push Docker no ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTION_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verificar identidade AWS
        run: aws sts get-caller-identity

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build da imagem Docker
        run: |
          docker build \
            -f ${{ env.DOCKERFILE_PATH }} \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest \
            ${{ env.DOCKER_BUILD_CONTEXT }}

      - name: Push da imagem Docker para o ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:frontend-${{ env.IMAGE_TAG }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:frontend-latest
