name: Deploy Applications

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      INFRA_ACTION_ROLE:
        required: true

env:
  AWS_REGION: 'us-east-1'
  EKS_CLUSTER_NAME: 'fiap-eks-cluster'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy no EKS
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.INFRA_ACTION_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar acesso ao EKS
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Verificar acesso ao cluster
        run: kubectl auth can-i '*' '*' --all-namespaces

      - name: Atualizar External Secrets
        run: |
          kubectl rollout restart deployment/external-secrets -n external-secrets
          kubectl rollout status deployment/external-secrets -n external-secrets --timeout=2m

      - name: Aplicar manifests
        run: |
          kubectl apply -f k8s/backend/application
          kubectl apply -f k8s/frontend/application

      - name: Reiniciar aplicações
        run: |
          kubectl rollout restart deployment/fiap-backend-deployment -n fiap-backend
          kubectl rollout restart deployment/fiap-frontend-deployment -n fiap-frontend

      - name: Aguardar deploy
        run: |
          kubectl rollout status deployment/fiap-backend-deployment -n fiap-backend --timeout=5m
          kubectl rollout status deployment/fiap-frontend-deployment -n fiap-frontend --timeout=5m
