name: Deploy Backend

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: './src/TechChallengeFase1.slnx'

on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restaurar dependências
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build da solução
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-build --verbosity normal
          
      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTION_ROLE_ARN }}
          aws-region: us-east-1
