name: 2. Destroy Expensive AWS Infrastructure

on:
  schedule:
    # GitHub Actions usa UTC: 03:00 UTC corresponde a 00:00 em São Paulo.
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy-kubernetes-infrastructure:
    name: Destroy Kubernetes Infrastructure
    uses: Maieru/fiap-tech-challenge-infra/.github/workflows/destroy-kubernetes-infrastructure.yml@main
    secrets:
      INFRA_ACTION_ROLE: ${{ secrets.INFRA_ACTION_ROLE }}
      REPOSITORIES_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}

  destroy-database:
    name: Destroy Database
    needs: destroy-kubernetes-infrastructure
    uses: Maieru/fiap-tech-challenge-db/.github/workflows/destroy-database.yml@main
    secrets:
      DATABASE_ACTION_ROLE: ${{ secrets.DATABASE_ACTION_ROLE }}
      db_username: ${{ secrets.db_username }}
      db_password: ${{ secrets.db_password }}
      REPOSITORIES_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}

  destroy-infrastructure:
    name: Destroy Expensive Infrastructure
    needs: destroy-database
    uses: Maieru/fiap-tech-challenge-infra/.github/workflows/destroy-expensive-infrastructure.yml@main
    secrets:
      INFRA_ACTION_ROLE: ${{ secrets.INFRA_ACTION_ROLE }}
      jwt_signing_key: ${{ secrets.jwt_signing_key }}
      REPOSITORIES_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
